services:
  web:
    env_file:
      - .env
    build: .
    command: sh -c 'python manage.py migrate &&
                gunicorn sportinj.wsgi:application --bind 0.0.0.0:8000'
    ports:
      - 8000:8000

  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
